// Code generated by "stringer -type=AuthMethod"; DO NOT EDIT

package conf

import "fmt"

const _AuthMethod_name = "AuthHeaderAuthToken"

var _AuthMethod_index = [...]uint8{0, 10, 19}

func (i AuthMethod) String() string {
	if i < 0 || i >= AuthMethod(len(_AuthMethod_index)-1) {
		return fmt.Sprintf("AuthMethod(%d)", i)
	}
	return _AuthMethod_name[_AuthMethod_index[i]:_AuthMethod_index[i+1]]
}
